app:
  env: dev
  debug: true

logger:
  level: debug
  format: console

database:
  postgres:
    host: localhost
    port: 5432
    database: mmmo_affiliate_db
    username: root
    password: 8000

  redis:
    host: localhost
    port: 6379
    password: ''

  elasticSearch:
    addresses:
      - http://localhost:9200

ai:
  url: http://localhost:8001
