app:
  env: qc
  debug: false

logger:
  level: info
  format: json

database:
  postgres:
    host: 1.1.1.1
    port: 5432
    database: mmmo_affiliate_qc
    username: qc_user
    password: ''

  redis:
    host: 1.1.1.1
    port: 6379

  elasticSearch:
    addresses:
      - http://1.1.1.1:9200
    enableLogging: false
